### ISSUE TITLE
Reference to a child Document - how to retrieve data?

### ISSUE THREAD

**Issue by grangoni** [hukusuke1007/flamingo#6]
Thank you for providing this library.
I'm a new user of it, and relatively new to firestore.

Could you please confirm the best way to deal with references todocuments  like in the image below ("ref" in "carts" (in the parent document) refers to another document  in "shopper" (child document))

![image](https://user-images.githubusercontent.com/53948849/81090579-41808300-8efe-11ea-905c-c80ba4078e8a.png)

Should i use the child Document's id as the reference?
If so, it seems ok to save the document with the reference it contains as a String with writeNotNull in the overriden toData method.
But when loading the document containing the reference from firestore, what is the best way to trigger also the loading of the child document refered to by the parent document?

Thanks in advance for your help

**Comment by hukusuke1007** [comment]
Thank you for a comment. I checked your question. 
I updated Flamingo since flamingo could not meet your requirement.

```txt
Added documentPath and collectionPath parameter in Document class.
```

Please update latest version.

・Sample code  
https://github.com/hukusuke1007/flamingo/blob/master/example/lib/model/shop/shop.dart#L7
https://github.com/hukusuke1007/flamingo/blob/master/example/lib/flamingo_test.dart#L1093

**Comment by hukusuke1007** [comment]
@grangoni Is it solve?

**Comment by hukusuke1007** [comment]
close
